config/routes.rb
Rails.application.routes.draw do
  
  
  root to: 'welcome#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :city
  resources :gossip do
    resources :likes
    resources :comments
  end
  resources :user
  resources :welcome
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :city_name, presence: true 
  validates :zip_code, presence: true 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes
  belongs_to :gossip
  belongs_to :tag, optional: true 

  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes
  has_many :tags, through: :tags_join_gossips
  has_many :comments

  validates :title, presence: true, length: {minimum: 3, maximum: 14}
  validates :content, presence: true, length: {minimum: 1}

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :gossips, through: :tags_join_gossips, dependent: :destroy


  validates :title, presence: true
end

app/models/tag_join_gossip.rb
class TagJoinGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag, optional: true
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  
  has_many :gossips
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  
  validates :age, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }, presence: true
  validates :description, presence: true
  
  has_secure_password
  validates :password, presence:true, length: {minimum:6}


  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end


end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
    
  end

  def show
    @city = City.find(params[:id])
    @gossips_select_by_id = Gossip.where(user_id:User.where(city_name:@city.city_name))
  end

  def new
    @city = City.new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def index
  @comments = Comment.all
end

def new
   @gossip = Gossip.find(params[:gossip_id]) 
  @comment = Comment.new
end

def edit
  @comment = Comment.find(params[:id])
end


def create
  @gossip = Gossip.find(params[:gossip_id])
  @comment = Comment.new(content: params[:content], gossip: @gossip)
  @comment.user = User.find_by(id: session[:user_id])

  if @comment.save 
    flash[:success] = "Votre commentaire vient d'ếtre publié avec succès"
    redirect_to gossip_path(@gossip.id)
  else
   redirect_to gossip_path(@gossip.id)
 end
end


def update
@comment = Comment.find(params[:id])
@gossip = Gossip.find(params[:gossip_id])

if @comment.update(content: params[:content])

  flash[:success] = "Votre potin a été modifié avec succès 👍"
  redirect_to gossip_path(@gossip.id)
else
  render 'edit'
end
end

def destroy
@gossip = Gossip.find(params[:gossip_id])
@comment = Comment.find(params[:id])


@comment.destroy
flash[:alert] = "Commentaire supprimé avec succès 🗑️"
redirect_to gossip_path(@gossip.id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/potins_helper.rb
module PotinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  
  end
  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end
  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/villes_helper.rb
module VillesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-6 mx-auto">
			
			<h3 class="card-title text-center m-4">Editer un commentaire</h3>

			
			<%= form_tag url_for(action: 'update'), method: "patch" do %>
			<%= label_tag 'Content' %>
			<%= text_area_tag 'content', @comment.content, class: "form-control" %>
			<br/>

			<%= submit_tag "Confirmer", class: "btn btn-primary" %>
			
			<%= link_to "Supprimer le commentaire", gossip_comment_path, data: {confirm: "Supprimer le commentaire ?"}, method: "delete", class: "btn btn-danger mb-0 ml-2" %>
			<% end %>

			
			<% if @comment.errors.any? %>

			<div class="alert alert-danger alert-dismissible fade show m-4" role="alert">
				<p><strong>ERREUR ! Voici les raisons :</strong></p>
				<ul>
					<% @comment.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<% end %>
				</ul>
			</div>

			<% end %>

		</div>
	</div>
</div>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>