config/routes.rb
Rails.application.routes.draw do
  
  
  root to: 'welcome#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :city
  resources :gossip do
    resources :likes
    resources :comments
  end
  resources :user
  resources :welcome
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :city_name, presence: true 
  validates :zip_code, presence: true 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes
  belongs_to :gossip
  belongs_to :tag, optional: true 

  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes
  has_many :tags, through: :tags_join_gossips
  has_many :comments

  validates :title, presence: true, length: {minimum: 3, maximum: 14}
  validates :content, presence: true, length: {minimum: 1}

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :gossips, through: :tags_join_gossips, dependent: :destroy


  validates :title, presence: true
end

app/models/tag_join_gossip.rb
class TagJoinGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag, optional: true
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  
  has_many :gossips
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  
  validates :age, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }, presence: true
  validates :description, presence: true
  
  has_secure_password
  validates :password, presence:true, length: {minimum:6}


  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end


end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
    
  end

  def show
    @city = City.find(params[:id])
    @gossips_select_by_id = Gossip.where(user_id:User.where(city_name:@city.city_name))
  end

  def new
    @city = City.new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  before_action :authenticate_user
  def index
    @id = params[:id]
    @gossips = Gossip.all
  end 
  
 

  def show
    @id= params[:id]
    @gossip = Gossip.find(params[:id])
    @comments = Gossip.find(params[:id]).comments
    @comment = Comment.new(content: params['content'], gossip_id: 1, gossip_id: @gossip ,user_id: 1)
  end
 
 
    def new
     @gossip = Gossip.new
     
    end
    
    def create
      
      @gossip = Gossip.new(title: params['title'], content: params['content'])
      @gossip.user = User.find_by(id: session[:user_id])

      if @gossip.save
        flash[:success] = "Potin créé avec succès"
        redirect_to welcome_index_path

      else
        flash[:danger] = "Nous n'avons pas réussi à créer votre potin"
        render new_gossip_path
      end
 end

    

  
    def edit
      @gossip = Gossip.find(params[:id])
    end
  
    def update
      @gossip = Gossip.find(params[:id])

      gossip_params = params.require(:gossip).permit(:title, :content)

      if  @gossip.user.id != current_user.id
        flash[:danger] = "Seul le créateur de ce gossip peut faire une modification. "
        redirect_to @gossip
      elsif @gossip.update(gossip_params)
        flash[:success] = "Gossip bien modifié!"
        redirect_to @gossip
      else
        flash[:danger] = "Nous n'avons pas réussi à modifier le potin !  #{@gossip.errors.full_messages.join(" , ")}"
        render :edit
      end
  end
  
    def destroy
      @gossip = Gossip.find(params[:id])
      if  @gossip.user.id != current_user.id
        flash[:danger] = "Seul le créateur de ce gossip peut supprimer le potin. "
        redirect_to @gossip
      else
      @gossip = Gossip.find(params[:id])
      @gossip.destroy
      flash[:success] = "Gossip bien supprimé!"
      redirect_to welcome_index_path
    end
  end
end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Veuillez vous connecter."
      redirect_to new_session_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/potins_helper.rb
module PotinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  
  end
  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end
  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/villes_helper.rb
module VillesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/edit.html.erb
<h1>Editer le gossip</h1>

<%= form_for @gossip do |f| %>
<div class="form-group">
    <label>Titre du potin</label><br>
    <%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
    <label>Contenu du potin</label><br>
    <%= f.text_area :content, class: "form-control" %>
</div>
<div class="form-group">
    <button type="submit" class="btn btn-primary">Modifier le potin </button>
<% end %>

app/views/gossip/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Titre du potin' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Contenu du potin' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />


      <%= submit_tag "Créer un potin" %>

    <% end %>

    </div>






  

app/views/gossip/show.html.erb
<h2>Auteur du gossip : <p class="author"><%= Gossip.find(@id).user.first_name %></p></h2>

<h2>Titre : <p class="author"><%= Gossip.find(@id).title %></p></h2>


<h2>Contenu : <p class="author"><%= Gossip.find(@id).content %></p></h2>

<h2>Ville: <a href = "<%=city_path(Gossip.find(@id).user.city.id)%>"><%= Gossip.find(@id).user.city.city_name %></a></h2>


<a href="/user/<%= Gossip.find(@id).user_id %>" class="btn btn-dark">Voir le profil de l'auteur</a>

<a href="/gossip/<%= Gossip.find(@id).id%>/edit" class="btn btn-dark">Modifier le potin</a>

<a href="/gossip/<%= Gossip.find(@id).id%>" class="btn btn-danger" data-confirm="Voulez-vous vraiment supprimer le potin ?" data-method="DELETE">Supprimer le potin</a>


						
<p><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
<% pre_like = @gossip.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', gossip_like_path(@gossip, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', gossip_likes_path(@gossip), method: :post %>
<% end %>
<h3> ESPACE COMMENTAIRES </h3>



<div class="container">

    
                <%= form_tag(gossip_comments_path(@id), method: "post") do %>
                    <%= text_field_tag 'gossip_id', @id, type: 'hidden', class: 'form-control' %>
					<%= text_field_tag 'user_id', current_user, type: 'hidden', class: 'form-control' %>
                    <div class="form-group">
                        <%= label_tag 'Nouveau commentaire' %>
                        <%= text_area_tag 'content', '', required: true, class: 'form-control' %>
                    </div>
                    <%= submit_tag "Envoyer", class: 'btn btn-outline-primary btn-sm' %>
                <% end %>
                

</div>

<div class="list-group mx-auto">

			<% @gossip.comments.reverse.each do |comment| %>
		
			<div class="list-group-item mb-2">
				<div class="row">
					<div class="col-9">
						<p class="mb-1"><%= comment.content %></p>
						<p class="mb-1"><%= comment.user.first_name %></p>

						
						
					</div>
					<div class="col-3 text-right">
					<%if current_user != nil%>
						<small><%= link_to "Editez", edit_gossip_comment_path(@gossip.id, comment.id) %></small>
						
						 <% end %>
					</div>
				</div>
			</div>
            <% end %>
			